name: homecagebehaviorENV
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - ipython
  - pip:
    - datajoint==0.14.1
    - easydict==1.10
    - h5py==2.10.0
    - hdf5storage==0.1.19
    - imageio==2.31.1
    - matplotlib==3.4.3
    - numba==0.53.1
    - numpy==1.19.5
    - pandas==1.3.0
    - pillow==10.0.0
    - pywavelets==1.4.1
    - requests==2.31.0
    - scikit-image==0.19.0
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - tensorflow==2.4
    - tqdm==4.65.0
    - umap-learn==0.5.3