---
# Configuration file used for behavior analysis (change accordingly)

# Location for where to save intermediate files during analysis
processing_folder: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\BehaviorModels\VERSION1\Animals


# whether to only run the datajoint part of the script for querying all trials from the lab database (run only on Windows)
only_run_datajoint: False

# Credentials for the Chenlab DataJoint database (if running on SCC, ignore)
datajoint_credentials:
  host: None
  user: None
  password: None


# Add full paths to each model and files used by the post processing DeepLabCut code
post_processing_dlc_paths:
  nose2tail_ae_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\Autoencoders\VERSION1\tm_nose_2_tail_markers_ae.h5
  feet_ae_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\Autoencoders\VERSION1\tm_feet_markers_ae.h5
  all_ae_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\Autoencoders\VERSION1\all_tm_markers_ae.h5

post_processing_dlc_params:
  # whether overwrite data if previously run
  overwrite: True
  # whether to save post analyzed dlc data to respective trial .mat files
  save2trialmat: True
  # disable tqdm progress bar from printing
  disable_progressbar: True


# version of motion mapper model used
motion_mapper_version: mm_v1

# Add full paths to each model and file used/generated by MotionMapper
motion_mapper_file_paths:
  auto_encoder_model_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\BehaviorModels\VERSION1\AE.h5
  umap_model_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\BehaviorModels\VERSION1\umap.model
  scaling_parameters_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\BehaviorModels\VERSION1\_trainMeanScale.npy
  look_up_table_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\BehaviorModels\VERSION1\BEHAVIOR_LABELED_LOOK_UP_TABLE.table
  watershed_file_path: Z:\Dropbox\Chen Lab Dropbox\Chen Lab Team Folder\Projects\Home_Cage_Training\DeepLabCut\BehaviorModels\VERSION1\zVals_wShed_groups_og.mat

motion_mapper_inference_params:
  # whether overwrite data if previously run
  overwrite: True
  # kernel size used to plot heatmap 
  sigma: 0.9 
  # whehter to save progress of motionmapper in animal processing folder
  save_progress: True
  # whether to save motionamapper data to respective trial .mat files
  save2trialmat: True
  # disable tqdm progress bar from printing
  disable_progressbar: True
  
  
# IMPORTANT NOTE:
# For running on SCC:
#    Enter list of animals to run behavior analysis. These list of animals should already have a folder in the "processing_folder"
#    with a .csv file that contains the trials queried from DataJoint
#    (If you want to run analysis on all animals in processing_folder, set first entry as "all") 
# 
# For running on local Windows
#    Enter list of animals to run behavior analysis on. These list of animals DO NOT need to have a folder in the "processing_folder"

animal_list:
  - 000C9522D76C
